### ISSUE TITLE
Tab view with form view?

### ISSUE THREAD

**Issue by millerbryan** [MaxGfeller/ampersand-tab-view#1]
Thank you for sharing this package.  It is exactly what I have been looking for and not yet savvy enough to develop.

I would like to place a view on the open tab which contains a form but I can't quite get the magic.  Any thoughts on a solid approach?

**Comment by MaxGfeller** [comment]
To be honest, it's been quite a while since i've made that package and i'm not even working with Ampersand anymore. But there is [an example](https://github.com/MaxGfeller/ampersand-tab-view/tree/master/example/app.js), which should make things clear, hopefully.

**Comment by millerbryan** [comment]
Thank you Max.  I was able to create the tabs as an outer view and then create the forms in an inner view and delegate control to the parent view.
